### ISSUE TITLE
知乎贴近屏幕底部的“跳过”按钮无法自动点击

### ISSUE THREAD

**Issue by TomoeMami** [xjunz/AutoSkip#2]
![Screenshot_20211004_144734_com zhihu android](https://user-images.githubusercontent.com/16950305/135805770-4a731376-41bb-45f9-9530-25df9513d88f.jpg)
如图，右下角的跳过无法自动点击

**Comment by DoveBoy** [comment]
同样的问题，类似的像京东在屏幕右下角`跳过`无法正常工作，以及显示的是`关闭`按钮也无法工作
