### ISSUE TITLE
能不能增加激活方式

### ISSUE THREAD

**Issue by Git-Psyduck** [xjunz/AutoSkip#9]
对于有root权限的手机，能不能增加直接使用root激活的方式？非常感谢

**Comment by ryuunoakaihitomi** [comment]
> 对于有root权限的手机，能不能增加直接使用root激活的方式？非常感谢

请查看[AppOps指南中的 为什么必须移除“root 模式” ](https://appops.rikka.app/zh-hans/guide/technical/system_behaviors/#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%BF%85%E9%A1%BB%E7%A7%BB%E9%99%A4-root-%E6%A8%A1%E5%BC%8F)部分

> 很多人会认为 root 无所不能，但实际上 root 只提供了一个 uid 0 的 shell。想要进入 Android 世界（直接使用 Java API），通过 app_process 运行 dex 几乎是唯一选择。
> “root 模式”的替代——“Shizuku 模式”使用 Shizuku做这一部分的工作。如果不使用 Shizuku，则仍然需要运行类似 Shizuku 的东西，这样做是没有意义的，并且也将带来无意义的资源使用。

这样做是没有意义的，并且也将带来无意义的资源使用。
